### ISSUE TITLE
SAML IDP group mappings Update not working as expected

### ISSUE THREAD

**Issue by jschoombee** [AxtonGrams/terraform-provider-wiz#39] opened 2022-11-22 15:27 UTC
### Terraform Version and Provider Version
`1.1.5` (also tried `1.3.5`)

### Affected Resource(s)
`wiz_saml_idp`

### Debug Output
[debug output](https://gist.github.com/jschoombee/0daa831251388fb13a12166a76ab8f9f)

### Expected Behavior
group mappings should be able to be updated/patched once they are in state

### Actual Behavior
group mappings are created fine on initial resource creation of `wiz_saml_idp`, subsequent updates however don't work. Believe this is actually more of a wiz  graph api issue. To fix it we need to add the below block to the graphql vars, otherwise Wiz panics with a not very useful message [1]
` "mergeGroupsMappingByRole":false,
        "allowManualRoleOverride":false,
        "useProviderManagedRoles":true`

[1] 
`[
│       {
│               "message": "oops! an internal error has occurred. for reference purposes, this is your request id: f8d050b0-52fe-4f74-bc72-1532a969f2f1",
│               "extensions": {
│                       "code": "DOWNSTREAM_SERVICE_ERROR",
│                       "exception": {
│                               "message": "oops! an internal error has occurred. for reference purposes, this is your request id: f8d050b0-52fe-4f74-bc72-1532a969f2f1"
│                       }
│               }
│       }
│ ]`

### Steps to Reproduce
1. create `wiz_saml_idp` with a `group_mapping`
2. either add or update an existing group_mapping

**Comment by gramsa49** [comment] 2022-11-22 15:56
Can you share a minimal HCL that can be used to reproduce the issue?  I am using the provider and managing group mappings without any issue.  Groups were last added to the mapping in the last couple of weeks in my deployment without issue.

Does the issue occur when adding a group mapping, or removing a group mapping, or both?

If you turn on debug logging in Terraform, you should see the API request body.  If you can share that, it would assist.  I understand if you cannot, or if it needs to be sanitized.

**Comment by jschoombee** [comment] 2022-11-22 17:14
Sure, the HCL indeed would have helped. For initial creation like below, it all works.

`resource "wiz_saml_idp" "test" {
  name                         = "tf-ping-dev"
  login_url                    = "https://sso-dev.company.com/idp/SSO.saml2"
  allow_manual_role_override   = false
  logout_url                   = ""
  use_provider_managed_roles   = true
  merge_groups_mapping_by_role = false
  certificate                  = <<EOT
-----BEGIN CERTIFICATE-----
*redacted*
-----END CERTIFICATE-----
EOT

  domains = [
    "company.com",
  ]

  group_mapping {
    provider_group_id = "CHOP"
    role = "PROJECT_READER"
    projects = [ "54000827-d3bf-5745-887b-417beb977cc9" ]
  }
}`

Also when removing a group mapping it is OK. When declaring the group mapping upon initial creation of the `wiz_saml_idp` resource it is OK. The challenge is *only* when adding/updating a mapping once it is in state. 

When trying to add another mapping is where it runs into trouble:
`
resource "wiz_saml_idp" "test" {
  name                         = "tf-ping-dev"
  login_url                    = "https://sso-dev.company.com/idp/SSO.saml2"
  allow_manual_role_override   = false
  logout_url                   = ""
  use_provider_managed_roles   = true
  merge_groups_mapping_by_role = false
  certificate                  = <<EOT
-----BEGIN CERTIFICATE-----
*redacted*
-----END CERTIFICATE-----
EOT

  domains = [
    "company.com",
  ]

  group_mapping {
    provider_group_id = "CHOP"
    role = "PROJECT_READER"
    projects = [ "54000827-d3bf-5745-887b-417beb977cc9" ]
  }
}
    group_mapping {
    provider_group_id = "ALL_AWS_AD_GROUP"
    role = "PROJECT_READER"
    projects = [ "9840623f-ec22-5ae5-8b71-05b9aa11c352" ]
  }
`

Line 41 of the gist shared has the [raw request](https://gist.github.com/jschoombee/0daa831251388fb13a12166a76ab8f9f#file-gistfile1-txt-L41) which looks absolutely fine, it is patching only what it should need to. This example is when trying to add a 2nd group mapping for `provider_group_ip` `ALL_AWS_AD_GROUP`. The same issue can be reproduced when trying to change the group mapping also, like changing the `provider_group_id` or list of `projects`. I can reproduce the Wiz error in  responsewhen calling the Graph API directly. It is only when I change the raw request to include 3 additional keys (which are included of course at initial creation):

example below mutation:
`mutation UpdateSAMLIdentityProvider($input: UpdateSAMLIdentityProviderInput!) { updateSAMLIdentityProvider(input: $input) { samlIdentityProvider { id } }}` with variables:

I had to explicitly add `useProviderManagedRoles`, `mergeGroupsMappingByRole` and `allowManualRoleOverride` keys  for me to get a non-error response 
`{
    "input":{
        "id":"tf-ping-dev",

        "patch":{
        "useProviderManagedRoles":true,
        "mergeGroupsMappingByRole":false,
       "allowManualRoleOverride":false,
        "groupMapping": [
                {
                    "providerGroupId":"CHOP",
                    "role":"PROJECT_READER",
                    "projects":["54000827-d3bf-5745-887b-417beb977cc9"]
                },
                {
                   "providerGroupId": "ALL_AWS_AD_GROUP",
                    "role": "PROJECT_READER",
                     "projects": [ "9840623f-ec22-5ae5-8b71-05b9aa11c352"  ]
                                }
            ],        
        }
            }
}`

Maybe its a wiz issue, specific to my regional endpoint `https://api.eu1.app.wiz.io/graphql` and/or the new cognito-backed IDP for their control plane auth `https://auth.app.wiz.io/oauth/token`. It would be interesting if there is a different behaviour in another region. I do think that it looks more like a bug on their side as it shouldn't be mandatory to pass these keys when patching I would think.

**Comment by jschoombee** [comment] 2022-11-24 10:16
Wiz suspects the issue is indeed on their end and that changes were made on the Cognito side. Will await their feedback

**Comment by jschoombee** [comment] 2022-11-30 13:21
Good news is that this affects `UpdateSAMLIdentityProvider` only. Below response from Wiz. Busy testing out the updated fix the next few days

_I got confirmation that this should only be a change to the mutation UpdateSAMLIdentityProvider, other mutations shouldn't be impacted.

Let me know if there are any other questions regarding this, thanks!_

**Comment by gramsa49** [comment] 2022-11-30 16:17
Do you have working code for this?  My team is now running into the same issue.  If you've started work on this, I can wait, or if not, I can generate a patch today.

**Comment by jschoombee** [comment] 2022-11-30 16:42
I have something I can share in the next hour or so. Long and short of it
is that idp fields, including optionals have to become mandatory and just
affects this SAML update mutation.

**Comment by gramsa49** [comment] 2022-11-30 17:43
I added comments to the PR.  Please review and let me know your thoughts.

**Comment by jschoombee** [comment] 2022-11-30 18:13
Reading your comments, I like the idea of keeping TF attribute schemas optional, aligning the graph schemas with the structs and then simply passing the TF attribute defaults. Will test out the `domains` if it's not needed, it was up until last time I checked on Friday still needed.

In the EU so its getting a bit late, will check first thing in the morning again, happy to make the necessary changes if its not fixed by then :)

**Comment by gramsa49** [comment] 2022-11-30 19:37
It looks like domain was deprecated.  It's no longer visible in the web interface when creation a saml idp config.  Also, when defined in the API, it is not written.  Creating an idp with a domain list, then reading it back, returns a null domain list.  Thinking domain should be marked as deprecated in the provider.

**Closed** 2022-11-30 21:19 UTC
Labels: bug

**Comment by gramsa49** [comment] 2022-11-30 21:22
I created a PR for the changes to address this issue.  I tested the changes and verified that updates/changes are handled properly.  I appreciate your effort trying to work up a solution, but I had to get a version out the door for my developers (delivery timelines); this turned into an issue that I had to address today.  Please keep contributing :)  You were on the right path with the proposed patch.
